[package]
name = "mk3-hal"
version = "0.1.0"
edition = "2024"

[dependencies]
rusb = "0.9"
hidapi = "2.6"
thiserror = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem", 
    "Win32_System_Pipes",
    "Win32_System_IO",
    "Win32_Security",
    "Win32_System_SystemServices"
] }
# Add std UDP socket support for NI service discovery
socket2 = "0.5"

[[example]]
name = "basic_test"
path = "examples/basic_test.rs"

[[example]]
name = "debug_input"
path = "examples/debug_input.rs"

[[example]]
name = "simple_test"
path = "examples/simple_test.rs"

[[example]]
name = "led_animation"
path = "examples/led_animation.rs"

[[example]]
name = "input_monitor"
path = "examples/input_monitor.rs"

[[example]]
name = "display_test"
path = "examples/display_test.rs"

[[example]]
name = "display_usb_test"
path = "examples/display_usb_test.rs"

[[example]]
name = "ni_ipc_test"
path = "examples/ni_ipc_test.rs"

[[example]]
name = "ni_udp_hack"
path = "examples/ni_udp_hack.rs"

[[example]]
name = "display_debug"
path = "examples/display_debug.rs"

[[example]]
name = "display_test2"
path = "examples/display_test2.rs"

[[example]]
name = "display_color_test"
path = "examples/display_color_test.rs"

[[example]]
name = "display_header_fix"
path = "examples/display_header_fix.rs"

[[example]]
name = "display_working_base"
path = "examples/display_working_base.rs"

[[example]]
name = "display_debug_colors"
path = "examples/display_debug_colors.rs"

[[example]]
name = "display_real_protocol"
path = "examples/display_real_protocol.rs"

[[example]]
name = "raw_loader"
path = "examples/raw_loader.rs"

[[example]]
name = "working_display"
path = "examples/working_display.rs"
