[package]
name = "mk3-hal"
version = "0.1.0"
edition = "2024"

[dependencies]
rusb = "0.9"
hidapi = "2.6"
thiserror = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem", 
    "Win32_System_Pipes",
    "Win32_System_IO",
    "Win32_Security",
    "Win32_System_SystemServices"
] }
# Add std UDP socket support for NI service discovery
socket2 = "0.5"

[[example]]
name = "basic_test"
path = "examples/basic_test.rs"

[[example]]
name = "debug_input"
path = "examples/debug_input.rs"

[[example]]
name = "simple_test"
path = "examples/simple_test.rs"

[[example]]
name = "led_animation"
path = "examples/led_animation.rs"

[[example]]
name = "input_monitor"
path = "examples/input_monitor.rs"

[[example]]
name = "display_test"
path = "examples/display_test.rs"

[[example]]
name = "display_usb_test"
path = "examples/display_usb_test.rs"

[[example]]
name = "ni_ipc_test"
path = "examples/ni_ipc_test.rs"

[[example]]
name = "ni_udp_hack"
path = "examples/ni_udp_hack.rs"

[[example]]
name = "raw_loader"
path = "examples/raw_loader.rs"

[[example]]
name = "working_display"
path = "examples/working_display.rs"

[[example]]
name = "red_green_animation"
path = "examples/red_green_animation.rs"
